classor/account/urls.py
from django.contrib.auth import views
from django.urls import path,reverse
from .views import ClassesList , ClassesCreate, EnrollClass, class_comment, class_classwork, class_student, class_teacher, TeacherEnrollClass, ClassesUpdate, ClassesDelete, StudentEnrollClass
from account import views as account_views
from django.conf.urls import url



app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('signup/', account_views.signup.as_view(), name='signup'),
    path('enroll/', EnrollClass.as_view(), name="enroll"),
    path('tenroll/', TeacherEnrollClass.as_view(), name="enroll_teacher"),
    path('senroll/', StudentEnrollClass.as_view(), name="enroll_student"),
    path('<slug:slug>/comments/',class_comment, name='comment'),
    path('<slug:slug>/classworks/',class_classwork, name='classwork'),
    path('<slug:slug>/students/',class_student, name='student'),
    path('<slug:slug>/teachers/',class_teacher, name='teachers'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

#    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
#    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

#    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
#    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
#    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
#    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += [
    path('', ClassesList.as_view(),name="home"),
    path('create/', ClassesCreate.as_view(),name="class-create"),
    path('update/<slug:slug>', ClassesUpdate.as_view(),name="class-update"),
    path('delete/<slug:slug>', ClassesDelete.as_view(),name="class-delete"),


]

classor/classor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from account import views as account_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls')),
    path('account/', include('account.urls')),
    url(r'^signup/$', account_views.signup, name='signup'),


]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classor/classroom/urls.py
from django.urls import path, re_path
from .views import classroom, api, class_detail, classroom2, TeacherList



app_name="classrooms"
urlpatterns = [
    path('',classroom,name="mainpage"),
    path('classroom2',classroom2,name="mainpage2"),
    path('<slug:slug>',class_detail,name="class_details"),

    path('api',api, name="api"),
    path('teacher/<slug:username>', TeacherList.as_view(), name="teacher"),
    path('teacher/<slug:username>/page/<int:page>', TeacherList.as_view(), name="teacher"),
]

classor/classroom/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter
from django.urls import reverse
from account.models import User, Profile
from .managers import  EnrolledManager
from cuser.middleware import CuserMiddleware


# Create your models here.

class class_room(models.Model):
    STATUS_CHOICES=(
        ('public','عمومی'),
        ('private','خصوصی'),
    )

    Name=models.CharField(max_length=200, verbose_name ="نام کلاس")
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='class_creator', verbose_name="ایجادکننده کلاس")
    class_number=models.SlugField(unique=True,verbose_name ="شماره کلاس")
    slug=models.SlugField(max_length=100,unique=True, verbose_name ="آدرس کلاس")
    section=models.CharField(max_length=200, verbose_name ="بخش")
    room=models.CharField(max_length=200, verbose_name ="اتاق")
    subject=models.CharField(max_length=200, verbose_name ="موضوع")
    startdate=models.DateTimeField(default=timezone.now, verbose_name ="تاریخ شروع کلاس")
    created_time=models.DateTimeField(auto_now_add=True, verbose_name ="تاریخ ایجاد")
    finished_time=models.DateTimeField(default=timezone.now, verbose_name ="تاریخ پایان کلاس")
    updated_time=models.DateTimeField(auto_now=True, verbose_name ="تاریخ آخرین آپدیت")
    status=models.CharField(max_length=7, choices=STATUS_CHOICES, verbose_name ="وضعیت انتشار")
    students=models.ManyToManyField(User, through='Enrolled', related_name='classstudents')
    teachers=models.ManyToManyField(User, through='EnrolledTeacher', related_name='classteachers')
#    teacher_members=models.ManyToManyField(User, blank=False, limit_choices_to={'role': 2}, related_name='teachers', verbose_name="لیست اساتید")


    class Meta:
        verbose_name = "کلاس"
        verbose_name_plural = "کلاس‌ها"

    def __str__(self):
        return self.Name

    def get_absolute_url(self):
        return reverse("account:home")

    def jcreated_time(self):
        return jalali_converter(self.created_time)

    def jstartdate(self):
        return jalali_converter(self.startdate)

    def save(self, *args, **kwargs):
        self.creator = CuserMiddleware.get_user()
        super(class_room,self).save(*args, **kwargs)




class Comment(models.Model):
    post = models.ForeignKey(class_room,null=False, on_delete=models.CASCADE,related_name='comments',verbose_name ="نام کلاس")
    name = models.CharField(null=True,verbose_name ="نام", max_length=80)
    body = models.TextField(null=True,verbose_name ="متن")
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='comment_creator', verbose_name="نام نظر‌دهنده")

    class Meta:
        ordering = ['created_on']
        verbose_name = "گفتگو"
        verbose_name_plural = "گفتگوها"
    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)
    def jcreated_on(self):
        return jalali_converter(self.created_on)
    def approve(self):
        self.approved_comment = True
        self.save()
    def save(self, *args, **kwargs):
        self.creator = CuserMiddleware.get_user()
        super(Comment,self).save(*args, **kwargs)


class Classworks(models.Model):
    classworks_post = models.ForeignKey(class_room,null=False, on_delete=models.CASCADE,related_name='classworks',verbose_name ="نام کلاس")
    classworks_name = models.CharField(null=True,verbose_name ="نام مبحث", max_length=80)
    classworks_body = models.TextField(null=True,verbose_name ="متن")
    classworks_created_on = models.DateTimeField(auto_now_add=True)
    classworks_active = models.BooleanField(default=True)
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='classwork_creator', verbose_name="نام استاد")

    class Meta:
        ordering = ['classworks_created_on']
        verbose_name = "تکلیف"
        verbose_name_plural = "تکالیف"
    def __str__(self):
        return 'Classwork {} by {}'.format(self.classworks_body, self.classworks_name)
    def classworks_jcreated_on(self):
        return jalali_converter(self.classworks_created_on)
    def approve(self):
        self.approved_comment = True
        self.save()
    def save(self, *args, **kwargs):
        self.creator = CuserMiddleware.get_user()
        super(Classworks,self).save(*args, **kwargs)


class Headings(models.Model):
    headingsـpost= models.ForeignKey(class_room,null=False, on_delete=models.CASCADE, related_name='headings',verbose_name="کلاس")
    headings_name= models.CharField(null=True,verbose_name="عنوان", max_length=200)

    class Meta:
        verbose_name= "عناوین"
        verbose_name_plural = "عناوین"
    def __str__(self):
        return self.headings_name


class SubHeadings(models.Model):
    subheadings_post= models.ForeignKey(Headings,null=False, on_delete=models.CASCADE, related_name='subheadings',verbose_name="عنوان")
    subheadings_name= models.CharField(null=True,verbose_name="زیر عنوان", max_length=200)

    class Meta:
        verbose_name= "زیر عنوان"
        verbose_name_plural = "زیر عناوین"
    def __str__(self):
        return self.subheadings_name


# class Membership(models.Model):
#    user = models.ForeignKey(User, on_delete=models.CASCADE)
#    class_students = models.ForeignKey(class_room, on_delete=models.CASCADE)
#    date_joined = models.DateField(auto_now_add=True, verbose_name="تاریخ عضویت")



class Enrolled(models.Model):
    student_profile = models.ForeignKey(User, related_name='students',on_delete=models.CASCADE,  null=True, blank=True,verbose_name="نام کاربری")
    classroom = models.ForeignKey(class_room, on_delete=models.CASCADE , related_name='classroom_enroll', null=True, blank=True, verbose_name="نام کلاس")
    date =models.DateTimeField(auto_now_add=True)
    previous_attempts = models.IntegerField(default=0)
    objects = EnrolledManager()

    class Meta:
        verbose_name = "دانش آموز کلاس"
        verbose_name_plural = "دانش آموزان کلاس"


    def __unicode__(self):
        return u'{0}'.format(self.student_profile)

    @staticmethod
    def autocomplete_search_fields():
        return (
            "student_profile__user__last_name__icontains",
            "student_profile__user__first_name__icontains",)

class EnrolledTeacher(models.Model):
    teacher_profile = models.ForeignKey(User, related_name='teachers',on_delete=models.CASCADE, null=True, blank=True ,verbose_name="نام کاربری")
    tclassroom = models.ForeignKey(class_room, on_delete=models.CASCADE, related_name='classroom_enrollteacher', null=True, blank=True, verbose_name="نام کلاس")
    date = models.DateTimeField(auto_now_add=True)
    previous_attempts = models.IntegerField(default=0)
    objects = EnrolledManager()

    class Meta:
        verbose_name = "استاد کلاس"
        verbose_name_plural = "اساتید کلاس"


    def __unicode__(self):
        return u'{0}'.format(self.teacher_profile)

    @staticmethod
    def autocomplete_search_fields():
        return (
            "teacher_profile__user__last_name__icontains",
            "teacher_profile__user__first_name__icontains",)

classor/classroom/forms.py
from .models import Comment, Classworks, Enrolled, EnrolledTeacher
from django import forms
from account.models import Profile
from .mixins import FieldsMixin

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body','name')

class ClassworksForm(forms.ModelForm, FieldsMixin):
    class Meta:
        model = Classworks
        fields = ('classworks_body','classworks_name')

class EnrollForm(forms.ModelForm):
    class Meta:
        model= Enrolled
        fields= ('student_profile',)

class TeacherEnrollForm(forms.ModelForm):
    class Meta:
        model= EnrolledTeacher
        fields= ('teacher_profile',)

classor/classroom/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView,DetailView
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from .models import class_room
from account.models import User
# Create your views here.

def classroom(request):
    context={
        "Class": class_room.objects.all()
    }
    return render(request,"classroom/classroom.html", context)

def classroom2(request):
    context={
        "Class": class_room.objects.all()
    }
    return render(request,"classroom/classroom2.html", context)




def class_detail(request, slug):

    context={
            "Classdetails": get_object_or_404(class_room, slug=slug)
}
    return render(request,"classroom/post2.html", context)




class TeacherList(ListView):
    paginate_by = 5
    template_name = 'classroom/teacher_list.html'

    def get_queryset(self):
        global teacher_list
        username = self.kwargs.get('username')
        teacher = get_object_or_404(User, username=username)
        return teacher.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context.data(**kwargs)
        context['teacher'] = teacher
        return context








def api(request):
    data= {
        "1": {
        "title": "hinew2",
        "id": 202,
        "slug": "first code"
        },
        "2": {
        "title": "hinew3",
        "id": 220,
        "slug": "sec code"
        },
        "3": {
        "title": "hinew",
        "id": 2220,
        "slug": "third code"
        },
    }
    return JsonResponse(data)

classor/classroom/templates/classroom/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

classor/classroom/templates/classroom/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>


  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>سیستم مدیریت کلاسور {% block title %} {% endblock %} </title>


  <!-- Favicons -->
  <link href="{% static 'classroom2/img/favicon.png' %}" rel="icon">
  <link href="{% static 'classroom2/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Vendor CSS Files -->
  <link href="{% static 'classroom2/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'classroom2/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'classroom2/vendor/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'classroom2/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'classroom2/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'classroom2/vendor/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'classroom2/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'classroom/css/rtl.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: DevFolio - v2.0.0
  * Template URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->



</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light " id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">لیست کلاسها</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>



{% block main %}
{% endblock %}

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'classroom/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'classroom/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'classroom/js/clean-blog.min.js' %}"></script>


    <!-- Vendor JS Files -->
    <script src="{% static 'classroom2/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'classroom2/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/typed.js/typed.min.js' %}"></script>
    <script src="{% static 'classroom2/vendor/venobox/venobox.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'classroom2/js/main.js' %}"></script>





</body>

</html>

classor/classroom/templates/classroom/classroom.html
{% extends 'classroom/base.html' %}
{% load static%}

{% block title %}

  {% endblock %}

{% block main %}

<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'classroom/img/home-bg.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>لیست کلاس‌های شما</h1>

        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    {% for Classdetails in Class %}
    <div class="post-preview">
     <a href="{% url 'classrooms:class_details' Classdetails.slug %}">
        <h2 class="post-title">
          {{Classdetails.Name}}
        </h2>
      </a>
      <p class="post-meta">تاریخ ایجاد کلاس:

      {{Classdetails.jcreated_time}}</p>
    </div>
    <hr>

    {% endfor %}

      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

classor/classroom/templates/classroom/classroom2.html
{% extends 'classroom/base.html' %}
{% load static%}



{% block main %}




    <!-- ======= Portfolio Section ======= -->


    <section id="work" class="portfolio-mf sect-pt4 route">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="title-box text-center">
              <h3 class="title-a">
                لیست کلاس‌ها
              </h3>
              <p class="subtitle-a">
                لیست کلاس‌هایی که در آن‌ها عضو هستید.
              </p>
              <div class="line-mf"></div>
            </div>
          </div>
        </div>
        <div class="row">
          {% for Classdetails in Class %}
          <div class="col-md-4">

            <div class="work-box">

              <a href="{% url 'classrooms:class_details' Classdetails.slug %}" >
                <div class="work-img">
                  <img src="{{Classdetails.thumbnail.url}}" alt="" class="img-fluid" >
                </div>
                <div class="work-content">
                  <div class="row">
                    <div class="col-sm-8">
                      <h1 class="w-title">{{Classdetails.Name}}</h1>
                      <div class="w-more">
                        <p class="w-ctegory">نام استاد: {{Classdetails.teacher.get_full_name}}</p>
                      </div>
                      <div class="w-more">
                        <span class="w-date">تاریخ عضویت: {{Classdetails.jcreated_time}}</span>
                      </div>
                    </div>

                    <div class="col-sm-4">
                      <div class="w-like">

                      </div>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

    </section><!-- End Portfolio Section -->




  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <div id="preloader"></div>


{% endblock %}

classor/classroom/templates/classroom/post.html
{% extends 'classroom/base.html' %}
{% load static%}

{% block title %} |
{{Classdetails.Name}}
 {% endblock %}
{% block main %}

<header class="masthead" style="background-image: url('{{Classdetails.thumbnail.url}}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>{{Classdetails.Name}}</h1>
          <span class="subheading">{{Classdetails.section}}</span>
        </div>
      </div>
    </div>
  </div>
</header>

<article>

  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="#">Active</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
    </li>
  </ul>





  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      {{Classdetails.posts|linebreaks}}
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      {{Classdetails.classwork|linebreaks}}
      </div>
    </div>
  </div>
</article>

{% endblock %}

classor/classroom/templates/classroom/teacher_list.html
{% extends 'classroom/list.html' %}
{% block header %}
  <h3 class="alert alert-primary text-center">لیست اساتید: {{teacher.get_full_name}}</h3>
{% endblock %}

{% block previous_page_url %}
  {% url 'classroom:teacher' teacher.username page_obj.previous_page_number %}
{% endblock %}

{% block previous_page_url %}
  {% url 'classroom:teacher' teacher.username page_obj.next_page_number %}
{% endblock %}  